package com.hyeona.widget;

import android.app.Activity; import android.app.AlertDialog; import android.graphics.Color; import android.os.Bundle; import android.os.Build; import android.Manifest; import android.content.pm.PackageManager; import android.text.InputType; import android.view.Gravity; import android.view.View; import android.widget.*; import java.text.SimpleDateFormat; import java.util.*; import java.util.concurrent.Executors;

public class MainActivity extends Activity {
 private final int ink=Color.rgb(40,55,59),muted=Color.rgb(107,140,145); private LinearLayout root,list; private ProgressBar loading; private String token="",section="calendar";
 @Override public void onCreate(Bundle s){super.onCreate(s);token=getSharedPreferences("prefs",MODE_PRIVATE).getString("token","");enablePinnedNotification();if(token.isEmpty())showToken();else showDashboard();}
 private void enablePinnedNotification(){if(Build.VERSION.SDK_INT>=33&&checkSelfPermission(Manifest.permission.POST_NOTIFICATIONS)!=PackageManager.PERMISSION_GRANTED)requestPermissions(new String[]{Manifest.permission.POST_NOTIFICATIONS},77);else NotificationKeeper.refresh(this);}
 @Override public void onRequestPermissionsResult(int r,String[] p,int[] g){super.onRequestPermissionsResult(r,p,g);if(r==77&&g.length>0&&g[0]==PackageManager.PERMISSION_GRANTED)NotificationKeeper.refresh(this);}
 private TextView text(String s,float z){TextView v=new TextView(this);v.setText(s);v.setTextSize(z);v.setTextColor(ink);return v;} private int dp(int n){return(int)(n*getResources().getDisplayMetrics().density+.5f);} private void pad(View v,int a,int b,int c,int d){v.setPadding(dp(a),dp(b),dp(c),dp(d));}
 private void showToken(){root=new LinearLayout(this);root.setOrientation(LinearLayout.VERTICAL);root.setBackgroundColor(Color.rgb(245,250,250));pad(root,24,42,24,24);root.addView(text("🌊 현아 위젯",28));TextView g=text("노션 대시보드를 갤럭시에서도 확인하고 수정해요.\nNotion 내부 통합 시크릿은 이 기기에만 저장됩니다.",15);g.setTextColor(muted);pad(g,0,18,0,24);root.addView(g);EditText i=field("Notion 내부 통합 시크릿","");i.setInputType(129);root.addView(i);Button b=new Button(this);b.setText("저장하고 대시보드 열기");root.addView(b);b.setOnClickListener(v->{token=i.getText().toString().trim();if(token.isEmpty()){toast("토큰을 입력해 주세요");return;}getSharedPreferences("prefs",MODE_PRIVATE).edit().putString("token",token).apply();WidgetUpdater.updateAll(this);showDashboard();});setContentView(root);}
 private void showDashboard(){root=new LinearLayout(this);root.setOrientation(LinearLayout.VERTICAL);root.setBackgroundColor(Color.rgb(250,252,252));LinearLayout h=new LinearLayout(this);h.setGravity(Gravity.CENTER_VERTICAL);pad(h,18,22,12,8);h.addView(text("hyeona's dashboard",21),new LinearLayout.LayoutParams(0,-2,1));Button set=new Button(this);set.setText("⚙");set.setOnClickListener(v->tokenDialog());h.addView(set,new LinearLayout.LayoutParams(dp(52),dp(48)));root.addView(h);HorizontalScrollView hs=new HorizontalScrollView(this);hs.setHorizontalScrollBarEnabled(false);LinearLayout tabs=new LinearLayout(this);pad(tabs,12,4,12,8);tab(tabs,"calendar","캘린더");tab(tabs,"bleeding","가계부");tab(tabs,"routine","루틴");tab(tabs,"wishlist","위시");tab(tabs,"memo","메모");tab(tabs,"brain","브레인덤프");hs.addView(tabs);root.addView(hs);loading=new ProgressBar(this);loading.setVisibility(View.GONE);root.addView(loading,new LinearLayout.LayoutParams(-1,dp(3)));ScrollView sc=new ScrollView(this);list=new LinearLayout(this);list.setOrientation(LinearLayout.VERTICAL);pad(list,18,12,18,32);sc.addView(list);root.addView(sc,new LinearLayout.LayoutParams(-1,0,1));setContentView(root);load();}
 private void tab(LinearLayout p,String k,String s){Button b=new Button(this);b.setText(s);b.setAllCaps(false);b.setOnClickListener(v->{section=k;load();});p.addView(b,new LinearLayout.LayoutParams(-2,dp(46)));}
 private void load(){list.removeAllViews();loading.setVisibility(View.VISIBLE);if(section.equals("brain")){brain();loading.setVisibility(View.GONE);return;}Executors.newSingleThreadExecutor().execute(()->{try{List<NotionClient.Item>x=NotionClient.query(token,section);runOnUiThread(()->render(x));}catch(Exception e){runOnUiThread(()->error(e));}});}
 private String heading(){switch(section){case"calendar":return"CALENDAR";case"bleeding":return"BLEEDING · 가계부";case"routine":return"ROUTINE";case"wishlist":return"WISHLIST";default:return"MEMO";}}
 private void render(List<NotionClient.Item> items){loading.setVisibility(View.GONE);list.removeAllViews();list.addView(text(heading(),23));TextView hint=text(section.equals("bleeding")?"이번 달 기록 · 누르면 수정, 길게 누르면 삭제":"누르면 수정 · 길게 누르면 삭제",12);hint.setTextColor(muted);pad(hint,0,3,0,12);list.addView(hint);Button add=new Button(this);add.setText("＋ 새 항목");add.setOnClickListener(v->edit(null));list.addView(add,new LinearLayout.LayoutParams(-1,dp(48)));if(items.isEmpty()){TextView e=text("아직 항목이 없어요 ♡",15);e.setGravity(Gravity.CENTER);pad(e,0,42,0,20);list.addView(e);}for(NotionClient.Item x:items)row(x);}
 private void row(NotionClient.Item x){LinearLayout r=new LinearLayout(this);r.setGravity(Gravity.CENTER_VERTICAL);r.setBackgroundColor(Color.WHITE);pad(r,10,8,10,8);if(section.equals("calendar")||section.equals("bleeding")||section.equals("routine")){CheckBox c=new CheckBox(this);c.setChecked(x.done);c.setOnClickListener(v->{x.done=c.isChecked();work("저장했어요",()->NotionClient.update(token,section,x));});r.addView(c);}String sub="";if(section.equals("calendar"))sub=x.date;if(section.equals("bleeding"))sub=((int)x.amount)+"만원"+(x.memo.isEmpty()?"":" · "+x.memo);if(section.equals("wishlist"))sub=x.status;TextView l=text(x.title+(sub.isEmpty()?"":"\n"+sub),16);if(x.done)l.setTextColor(Color.GRAY);r.addView(l,new LinearLayout.LayoutParams(0,dp(58),1));r.setOnClickListener(v->edit(x));r.setOnLongClickListener(v->{remove(x);return true;});LinearLayout.LayoutParams p=new LinearLayout.LayoutParams(-1,-2);p.setMargins(0,dp(8),0,0);list.addView(r,p);}
 private EditText field(String hint,String value){EditText e=new EditText(this);e.setHint(hint);e.setText(value==null?"":value);return e;}
 private void edit(NotionClient.Item old){NotionClient.Item x=old==null?new NotionClient.Item():old.copy();LinearLayout f=new LinearLayout(this);f.setOrientation(LinearLayout.VERTICAL);pad(f,20,8,20,0);EditText title=field(section.equals("memo")?"메모 제목":"항목 이름",x.title);f.addView(title);EditText extra=null,memo=null;CheckBox done=null;if(section.equals("calendar")){extra=field("날짜 (예: 2026-09-01)",old==null?new SimpleDateFormat("yyyy-MM-dd",Locale.US).format(new Date()):x.date);f.addView(extra);}if(section.equals("bleeding")){extra=field("금액 (만원)",old==null?"":String.valueOf(x.amount));extra.setInputType(InputType.TYPE_CLASS_NUMBER|InputType.TYPE_NUMBER_FLAG_DECIMAL|InputType.TYPE_NUMBER_FLAG_SIGNED);f.addView(extra);memo=field("메모",x.memo);f.addView(memo);}if(section.equals("wishlist")){extra=field("상태 (예: 시작 전 / 완료)",x.status);f.addView(extra);}if(section.equals("calendar")||section.equals("bleeding")||section.equals("routine")){done=new CheckBox(this);done.setText("완료");done.setChecked(x.done);f.addView(done);}final EditText ex=extra,me=memo;final CheckBox dn=done;new AlertDialog.Builder(this).setTitle(old==null?"새 항목":"항목 수정").setView(f).setNegativeButton("취소",null).setPositiveButton("저장",(d,w)->{x.title=title.getText().toString().trim();if(x.title.isEmpty()){toast("이름을 입력해 주세요");return;}if(section.equals("calendar"))x.date=ex.getText().toString().trim();if(section.equals("bleeding")){try{x.amount=Double.parseDouble(ex.getText().toString().trim());}catch(Exception q){x.amount=0;}x.memo=me.getText().toString().trim();x.month=new SimpleDateFormat("M월",Locale.KOREAN).format(new Date());}if(section.equals("wishlist"))x.status=ex.getText().toString().trim();if(dn!=null)x.done=dn.isChecked();work("저장했어요",()->{if(old==null)NotionClient.create(token,section,x);else NotionClient.update(token,section,x);});}).show();}
 private void remove(NotionClient.Item x){new AlertDialog.Builder(this).setTitle("삭제할까요?").setMessage(x.title).setNegativeButton("취소",null).setPositiveButton("삭제",(d,w)->work("삭제했어요",()->NotionClient.delete(token,x.id))).show();}
 private interface Work{void run()throws Exception;}private void work(String ok,Work w){loading.setVisibility(View.VISIBLE);Executors.newSingleThreadExecutor().execute(()->{try{w.run();runOnUiThread(()->{toast(ok);load();WidgetUpdater.updateAll(this);});}catch(Exception e){runOnUiThread(()->error(e));}});}
 private void brain(){list.removeAllViews();list.addView(text("BRAIN DUMP",23));TextView h=text("입력 내용은 즉시 이 기기에 보관되고, 저장 버튼을 누르면 노션에도 반영돼요.",12);h.setTextColor(muted);pad(h,0,3,0,12);list.addView(h);EditText body=field("아무거나 그냥 적어",getSharedPreferences("prefs",MODE_PRIVATE).getString("brainDraft",""));body.setGravity(Gravity.TOP);body.setMinLines(12);body.setBackgroundColor(Color.WHITE);pad(body,14,14,14,14);list.addView(body,new LinearLayout.LayoutParams(-1,dp(280)));body.addTextChangedListener(new android.text.TextWatcher(){public void beforeTextChanged(CharSequence s,int a,int b,int c){}public void onTextChanged(CharSequence s,int a,int b,int c){getSharedPreferences("prefs",MODE_PRIVATE).edit().putString("brainDraft",s.toString()).apply();}public void afterTextChanged(android.text.Editable e){}});Button save=new Button(this);save.setText("노션에 저장");save.setOnClickListener(v->work("브레인덤프를 저장했어요",()->NotionClient.saveBrain(token,body.getText().toString())));list.addView(save,new LinearLayout.LayoutParams(-1,dp(52)));Executors.newSingleThreadExecutor().execute(()->{try{String remote=NotionClient.loadBrain(token);runOnUiThread(()->{if(body.getText().length()==0)body.setText(remote);});}catch(Exception e){runOnUiThread(()->toast("노션 불러오기 실패 · 기기 보관본은 유지돼요"));}});}
 private void tokenDialog(){EditText i=field("Notion 내부 통합 시크릿",token);i.setInputType(129);new AlertDialog.Builder(this).setTitle("연결 설정").setView(i).setNegativeButton("취소",null).setNeutralButton("토큰 지우기",(d,w)->{getSharedPreferences("prefs",MODE_PRIVATE).edit().clear().apply();token="";showToken();}).setPositiveButton("저장",(d,w)->{token=i.getText().toString().trim();getSharedPreferences("prefs",MODE_PRIVATE).edit().putString("token",token).apply();load();}).show();}
 private void error(Exception e){loading.setVisibility(View.GONE);toast("오류: "+(e.getMessage()==null?"알 수 없는 오류":e.getMessage()));}private void toast(String s){Toast.makeText(this,s,Toast.LENGTH_LONG).show();}
}
