package com.hyeona.widget;

import android.app.Activity; import android.app.AlertDialog; import android.graphics.Color; import android.os.Bundle; import android.os.Build; import android.Manifest; import android.content.pm.PackageManager; import android.text.InputType; import android.view.Gravity; import android.view.View; import android.widget.*; import java.text.SimpleDateFormat; import java.util.*; import java.util.concurrent.Executors;

public class MainActivity extends Activity {
 @Override protected void onNewIntent(android.content.Intent intent){super.onNewIntent(intent);setIntent(intent);String requested=intent.getStringExtra("section");if(requested!=null)section=requested;if(!token.isEmpty())showDashboard();}
 private final int ink=Color.rgb(40,55,59),muted=Color.rgb(107,140,145); private LinearLayout root,list; private ProgressBar loading; private String token="",section="calendar";
 @Override public void onCreate(Bundle s){super.onCreate(s);token=getSharedPreferences("prefs",MODE_PRIVATE).getString("token","");String requested=getIntent().getStringExtra("section");if(requested!=null&&!requested.isEmpty())section=requested;enablePinnedNotification();if(token.isEmpty())showToken();else {showDashboard();WidgetUpdater.updateAll(this);}}
 private void enablePinnedNotification(){if(Build.VERSION.SDK_INT>=33&&checkSelfPermission(Manifest.permission.POST_NOTIFICATIONS)!=PackageManager.PERMISSION_GRANTED)requestPermissions(new String[]{Manifest.permission.POST_NOTIFICATIONS},77);else NotificationKeeper.refresh(this);}
 @Override public void onRequestPermissionsResult(int r,String[] p,int[] g){super.onRequestPermissionsResult(r,p,g);if(r==77&&g.length>0&&g[0]==PackageManager.PERMISSION_GRANTED)NotificationKeeper.refresh(this);}
 private TextView text(String s,float z){TextView v=new TextView(this);v.setText(s);v.setTextSize(z);v.setTextColor(ink);return v;} private int dp(int n){return(int)(n*getResources().getDisplayMetrics().density+.5f);} private void pad(View v,int a,int b,int c,int d){v.setPadding(dp(a),dp(b),dp(c),dp(d));}
 private void showToken(){root=new LinearLayout(this);root.setOrientation(LinearLayout.VERTICAL);root.setBackgroundColor(Color.rgb(245,250,250));pad(root,24,42,24,24);root.addView(text("🌊 현아 위젯",28));TextView g=text("노션 대시보드를 갤럭시에서도 확인하고 수정해요.\nNotion 내부 통합 시크릿은 이 기기에만 저장됩니다.",15);g.setTextColor(muted);pad(g,0,18,0,24);root.addView(g);EditText i=field("Notion 내부 통합 시크릿","");i.setInputType(129);root.addView(i);Button b=new Button(this);b.setText("저장하고 대시보드 열기");root.addView(b);b.setOnClickListener(v->{token=i.getText().toString().trim();if(token.isEmpty()){toast("토큰을 입력해 주세요");return;}getSharedPreferences("prefs",MODE_PRIVATE).edit().putString("token",token).apply();WidgetUpdater.updateAll(this);showDashboard();});setContentView(root);}
 private void showDashboard(){root=new LinearLayout(this);root.setOrientation(LinearLayout.VERTICAL);root.setBackgroundColor(Color.rgb(250,252,252));LinearLayout h=new LinearLayout(this);h.setGravity(Gravity.CENTER_VERTICAL);pad(h,18,22,12,8);h.addView(text("hyeona's dashboard",21),new LinearLayout.LayoutParams(0,-2,1));Button set=new Button(this);set.setText("⚙");set.setOnClickListener(v->tokenDialog());h.addView(set,new LinearLayout.LayoutParams(dp(52),dp(48)));root.addView(h);HorizontalScrollView hs=new HorizontalScrollView(this);hs.setHorizontalScrollBarEnabled(false);LinearLayout tabs=new LinearLayout(this);pad(tabs,12,4,12,8);tab(tabs,"calendar","캘린더");tab(tabs,"todo","오늘 할 일");tab(tabs,"bleeding","가계부");tab(tabs,"routine","루틴");tab(tabs,"wishlist","위시");tab(tabs,"memo","메모");tab(tabs,"brain","브레인덤프");tab(tabs,"care","관리");hs.addView(tabs);root.addView(hs);loading=new ProgressBar(this);loading.setVisibility(View.GONE);root.addView(loading,new LinearLayout.LayoutParams(-1,dp(3)));ScrollView sc=new ScrollView(this);list=new LinearLayout(this);list.setOrientation(LinearLayout.VERTICAL);pad(list,18,12,18,32);sc.addView(list);root.addView(sc,new LinearLayout.LayoutParams(-1,0,1));setContentView(root);Button refresh=new Button(this);refresh.setText("새로고침 · 위젯 동기화");refresh.setOnClickListener(v->{load();WidgetUpdater.updateAll(this);});root.addView(refresh);load();if(section.equals("calendar")&&getIntent().getBooleanExtra("add_event",false)){getIntent().removeExtra("add_event");calendarEditor(null);}}
 private void tab(LinearLayout p,String k,String s){Button b=new Button(this);b.setText(s);b.setAllCaps(false);b.setOnClickListener(v->{section=k;if(k.equals("care"))getIntent().removeExtra("care_field");if(k.equals("calendar"))getIntent().removeExtra("calendar_date");load();});p.addView(b,new LinearLayout.LayoutParams(-2,dp(46)));}
 private void load(){list.removeAllViews();loading.setVisibility(View.VISIBLE);if(section.equals("brain")){brain();loading.setVisibility(View.GONE);return;}if(section.equals("care")){care();loading.setVisibility(View.GONE);return;}Executors.newSingleThreadExecutor().execute(()->{try{List<NotionClient.Item>x=NotionClient.query(token,section);runOnUiThread(()->render(x));}catch(Exception e){runOnUiThread(()->error(e));}});}
 private String heading(){switch(section){case"calendar":return getIntent().getStringExtra("calendar_date")==null?"캘린더":getIntent().getStringExtra("calendar_date")+" 일정";case"todo":return"TODAY";case"bleeding":return"BLEEDING · 가계부";case"routine":return"ROUTINE";case"wishlist":return"WISHLIST";default:return"MEMO";}}
 private void render(List<NotionClient.Item> items){String selectedDate=getIntent().getStringExtra("calendar_date");if(section.equals("calendar")&&selectedDate!=null){List<NotionClient.Item> filtered=new ArrayList<>();for(NotionClient.Item item:items)if(item.date.startsWith(selectedDate))filtered.add(item);items=filtered;}loading.setVisibility(View.GONE);list.removeAllViews();list.addView(text(heading(),23));TextView hint=text(section.equals("bleeding")?"이번 달 기록 · 누르면 수정, 길게 누르면 삭제":"누르면 상세 보기 · 길게 누르면 삭제",12);hint.setTextColor(muted);pad(hint,0,3,0,12);list.addView(hint);Button add=new Button(this);add.setText("＋ 새 항목");add.setOnClickListener(v->edit(null));list.addView(add,new LinearLayout.LayoutParams(-1,dp(48)));if(items.isEmpty()){TextView e=text("아직 항목이 없어요 ♡",15);e.setGravity(Gravity.CENTER);pad(e,0,42,0,20);list.addView(e);}for(NotionClient.Item x:items)row(x);}
 private void row(NotionClient.Item x){LinearLayout r=new LinearLayout(this);r.setGravity(Gravity.CENTER_VERTICAL);r.setBackgroundColor(Color.WHITE);pad(r,10,8,10,8);if(section.equals("calendar")||section.equals("bleeding")||section.equals("routine")||section.equals("todo")){CheckBox c=new CheckBox(this);c.setChecked(x.done);c.setOnClickListener(v->{x.done=c.isChecked();work("저장했어요",()->NotionClient.update(token,section,x));});r.addView(c);}String sub="";if(section.equals("calendar"))sub=x.date;if(section.equals("bleeding"))sub=((int)x.amount)+"만원"+(x.memo.isEmpty()?"":" · "+x.memo);if(section.equals("wishlist"))sub=x.status;TextView l=text(x.title+(sub.isEmpty()?"":"\n"+sub),16);if(x.done)l.setTextColor(Color.GRAY);r.addView(l,new LinearLayout.LayoutParams(0,dp(58),1));r.setOnClickListener(v->showDetail(x));r.setOnLongClickListener(v->{remove(x);return true;});LinearLayout.LayoutParams p=new LinearLayout.LayoutParams(-1,-2);p.setMargins(0,dp(8),0,0);list.addView(r,p);}
 private void showDetail(NotionClient.Item item){
  LinearLayout body=new LinearLayout(this);body.setOrientation(LinearLayout.VERTICAL);pad(body,20,12,20,20);TextView content=text("불러오는 중…",16);content.setTextIsSelectable(true);body.addView(content);ScrollView scroll=new ScrollView(this);scroll.addView(body);
  AlertDialog dialog=new AlertDialog.Builder(this).setTitle(item.title).setView(scroll).setNegativeButton("닫기",null).setPositiveButton("항목 수정",(d,w)->edit(item)).setNeutralButton("노션에서 보기",(d,w)->startActivity(new android.content.Intent(android.content.Intent.ACTION_VIEW,android.net.Uri.parse("https://www.notion.so/"+item.id.replace("-",""))))).create();dialog.show();
  Executors.newSingleThreadExecutor().execute(()->{try{String detail=NotionClient.loadDetail(token,item.id);runOnUiThread(()->content.setText((item.date.isEmpty()?"":item.date+"\n\n")+detail));}catch(Exception e){runOnUiThread(()->{content.setText("본문을 불러오지 못했어요.\n"+e.getMessage()+"\n\n눌러 다시 시도");content.setOnClickListener(v->{dialog.dismiss();showDetail(item);});});}});
 }
 private EditText field(String hint,String value){EditText e=new EditText(this);e.setHint(hint);e.setText(value==null?"":value);return e;}
 private void edit(NotionClient.Item old){if(section.equals("calendar")){calendarEditor(old);return;}NotionClient.Item x=old==null?new NotionClient.Item():old.copy();LinearLayout f=new LinearLayout(this);f.setOrientation(LinearLayout.VERTICAL);pad(f,20,8,20,0);EditText title=field(section.equals("memo")?"메모 제목":"항목 이름",x.title);f.addView(title);EditText extra=null,memo=null;CheckBox done=null;if(section.equals("calendar")){extra=field("날짜 (예: 2026-09-01)",old==null?new SimpleDateFormat("yyyy-MM-dd",Locale.US).format(new Date()):x.date);f.addView(extra);}if(section.equals("bleeding")){extra=field("금액 (만원)",old==null?"":String.valueOf(x.amount));extra.setInputType(InputType.TYPE_CLASS_NUMBER|InputType.TYPE_NUMBER_FLAG_DECIMAL|InputType.TYPE_NUMBER_FLAG_SIGNED);f.addView(extra);memo=field("메모",x.memo);f.addView(memo);}if(section.equals("wishlist")){extra=field("상태 (예: 시작 전 / 완료)",x.status);f.addView(extra);}if(section.equals("calendar")||section.equals("bleeding")||section.equals("routine")||section.equals("todo")){done=new CheckBox(this);done.setText("완료");done.setChecked(x.done);f.addView(done);}final EditText ex=extra,me=memo;final CheckBox dn=done;new AlertDialog.Builder(this).setTitle(old==null?"새 항목":"항목 수정").setView(f).setNegativeButton("취소",null).setPositiveButton("저장",(d,w)->{x.title=title.getText().toString().trim();if(x.title.isEmpty()){toast("이름을 입력해 주세요");return;}if(section.equals("calendar"))x.date=ex.getText().toString().trim();if(section.equals("bleeding")){try{x.amount=Double.parseDouble(ex.getText().toString().trim());}catch(Exception q){x.amount=0;}x.memo=me.getText().toString().trim();x.month=new SimpleDateFormat("M월",Locale.KOREAN).format(new Date());}if(section.equals("wishlist"))x.status=ex.getText().toString().trim();if(dn!=null)x.done=dn.isChecked();work("저장했어요",()->{if(old==null)NotionClient.create(token,section,x);else NotionClient.update(token,section,x);});}).show();}

 private void calendarEditor(NotionClient.Item old){
  final NotionClient.Item item=old==null?new NotionClient.Item():old.copy();
  String initial=old==null?getIntent().getStringExtra("calendar_date"):item.date;
  if(initial==null||initial.length()<10)initial=new SimpleDateFormat("yyyy-MM-dd",Locale.US).format(new Date());
  final String[] picked={initial.substring(0,10)};
  LinearLayout form=new LinearLayout(this);form.setOrientation(LinearLayout.VERTICAL);pad(form,20,8,20,8);
  EditText title=field("일정 제목",item.title);title.setTextSize(18);title.setMinHeight(dp(52));form.addView(title);
  Button dateButton=new Button(this);dateButton.setText(picked[0]+" · 날짜 변경");form.addView(dateButton);
  dateButton.setOnClickListener(v->{String[] parts=picked[0].split("-");new android.app.DatePickerDialog(this,(picker,y,m,d)->{picked[0]=String.format(Locale.US,"%04d-%02d-%02d",y,m+1,d);dateButton.setText(picked[0]+" · 날짜 변경");},Integer.parseInt(parts[0]),Integer.parseInt(parts[1])-1,Integer.parseInt(parts[2])).show();});
  AlertDialog dialog=new AlertDialog.Builder(this).setTitle(old==null?"일정 추가":"일정 수정").setView(form).setNegativeButton("취소",null).setPositiveButton("저장",null).create();
  dialog.setOnShowListener(unused->dialog.getButton(AlertDialog.BUTTON_POSITIVE).setOnClickListener(v->{
   String value=title.getText().toString().trim();if(value.isEmpty()){title.setError("일정 제목을 입력해 주세요");return;}
   item.title=value;item.date=picked[0];Button save=dialog.getButton(AlertDialog.BUTTON_POSITIVE);save.setEnabled(false);dialog.setCancelable(false);
   Executors.newSingleThreadExecutor().execute(()->{try{if(old==null)NotionClient.create(token,"calendar",item);else NotionClient.update(token,"calendar",item);WidgetUpdater.updateAll(this);runOnUiThread(()->{dialog.dismiss();toast("일정을 저장했어요");if(section.equals("calendar"))load();});}catch(Exception e){runOnUiThread(()->{save.setEnabled(true);dialog.setCancelable(true);title.setError("저장 실패: "+e.getMessage());});}});
  }));dialog.show();
 }

 private void remove(NotionClient.Item x){new AlertDialog.Builder(this).setTitle("삭제할까요?").setMessage(x.title).setNegativeButton("취소",null).setPositiveButton("삭제",(d,w)->work("삭제했어요",()->NotionClient.delete(token,x.id))).show();}
 private interface Work{void run()throws Exception;}private void work(String ok,Work w){loading.setVisibility(View.VISIBLE);Executors.newSingleThreadExecutor().execute(()->{try{w.run();runOnUiThread(()->{toast(ok);load();WidgetUpdater.updateAll(this);});}catch(Exception e){runOnUiThread(()->error(e));}});}
 private void brain(){list.removeAllViews();list.addView(text("BRAIN DUMP",23));TextView h=text("입력 내용은 즉시 이 기기에 보관되고, 저장 버튼을 누르면 노션에도 반영돼요.",12);h.setTextColor(muted);pad(h,0,3,0,12);list.addView(h);EditText body=field("아무거나 그냥 적어",getSharedPreferences("prefs",MODE_PRIVATE).getString("brainDraft",""));body.setGravity(Gravity.TOP);body.setMinLines(12);body.setBackgroundColor(Color.WHITE);pad(body,14,14,14,14);list.addView(body,new LinearLayout.LayoutParams(-1,dp(280)));body.addTextChangedListener(new android.text.TextWatcher(){public void beforeTextChanged(CharSequence s,int a,int b,int c){}public void onTextChanged(CharSequence s,int a,int b,int c){getSharedPreferences("prefs",MODE_PRIVATE).edit().putString("brainDraft",s.toString()).apply();}public void afterTextChanged(android.text.Editable e){}});Button save=new Button(this);save.setText("노션에 저장");save.setOnClickListener(v->work("브레인덤프를 저장했어요",()->NotionClient.saveBrain(token,body.getText().toString())));list.addView(save,new LinearLayout.LayoutParams(-1,dp(52)));Executors.newSingleThreadExecutor().execute(()->{try{String remote=NotionClient.loadBrain(token);runOnUiThread(()->{if(body.getText().length()==0)body.setText(remote);});}catch(Exception e){runOnUiThread(()->toast("노션 불러오기 실패 · 기기 보관본은 유지돼요"));}});}
 private void care(){
  String mealField=getIntent().getStringExtra("care_field");if(mealField!=null){singleMeal(mealField);return;}
  list.removeAllViews();
  String picked=getIntent().getStringExtra("care_date");if(picked==null||picked.isEmpty())picked=new SimpleDateFormat("yyyy-MM-dd",Locale.US).format(new Date());final String date=picked;

  list.addView(text(date+" 식단",23));
  LinearLayout cycleFields=new LinearLayout(this);cycleFields.setOrientation(LinearLayout.VERTICAL);cycleFields.setVisibility(View.GONE);
  Button cycleToggle=new Button(this);cycleToggle.setText("생리 주기 설정");cycleToggle.setOnClickListener(v->cycleFields.setVisibility(cycleFields.getVisibility()==View.VISIBLE?View.GONE:View.VISIBLE));list.addView(cycleToggle);list.addView(cycleFields);
  TextView cycleHint=text("생리 주기",13);cycleHint.setTextColor(muted);pad(cycleHint,0,8,0,3);cycleFields.addView(cycleHint);
  String sv=getSharedPreferences("prefs",MODE_PRIVATE).getString("period_start","");
  String ev=getSharedPreferences("prefs",MODE_PRIVATE).getString("period_end","");
  int cv=getSharedPreferences("prefs",MODE_PRIVATE).getInt("cycle_length",28);
  EditText periodStart=field("생리 시작일 (2026-09-01)",sv);
  EditText periodEnd=field("생리 종료일 (2026-09-05)",ev);
  EditText cycle=field("평균 주기",String.valueOf(cv));cycle.setInputType(InputType.TYPE_CLASS_NUMBER);
  cycleFields.addView(periodStart);cycleFields.addView(periodEnd);cycleFields.addView(cycle);
  Button cycleSave=new Button(this);cycleSave.setText("생리 주기 저장");
  cycleSave.setOnClickListener(v->{int days;try{days=Integer.parseInt(cycle.getText().toString().trim());}catch(Exception e){days=28;}days=Math.max(21,Math.min(45,days));getSharedPreferences("prefs",MODE_PRIVATE).edit().putString("period_start",periodStart.getText().toString().trim()).putString("period_end",periodEnd.getText().toString().trim()).putInt("cycle_length",days).putInt("care_week_offset",0).apply();WidgetUpdater.updateAll(this);toast("생리 주기를 저장했어요");});
  cycleFields.addView(cycleSave,new LinearLayout.LayoutParams(-1,dp(48)));

  String phase=carePhase(date);TextView h=text(date+(phase.isEmpty()?"":"  "+phase)+"\n식단은 기기에 먼저 저장되고 노션에도 동기화돼요.",12);h.setTextColor(muted);pad(h,0,12,0,8);list.addView(h);
  EditText breakfast=field("아침","");breakfast.setMinLines(2);breakfast.setGravity(Gravity.TOP);list.addView(breakfast,new LinearLayout.LayoutParams(-1,dp(76)));
  EditText lunch=field("점심","");lunch.setMinLines(2);lunch.setGravity(Gravity.TOP);list.addView(lunch,new LinearLayout.LayoutParams(-1,dp(76)));
  EditText dinner=field("저녁","");dinner.setMinLines(2);dinner.setGravity(Gravity.TOP);list.addView(dinner,new LinearLayout.LayoutParams(-1,dp(76)));
  EditText snack=field("간식","");snack.setMinLines(2);snack.setGravity(Gravity.TOP);list.addView(snack,new LinearLayout.LayoutParams(-1,dp(76)));
  EditText note=field("관리 메모","");note.setMinLines(3);note.setGravity(Gravity.TOP);list.addView(note,new LinearLayout.LayoutParams(-1,dp(108)));

  final NotionClient.CareEntry[] current={loadLocalCare(date)};
  breakfast.setText(current[0].breakfast);lunch.setText(current[0].lunch);dinner.setText(current[0].dinner);snack.setText(current[0].snack);note.setText(current[0].note);

  final boolean[] edited={false};
  android.text.TextWatcher dirty=new android.text.TextWatcher(){public void beforeTextChanged(CharSequence s,int a,int b,int c){}public void onTextChanged(CharSequence s,int a,int b,int c){edited[0]=true;}public void afterTextChanged(android.text.Editable e){}};
  for(EditText input:new EditText[]{breakfast,lunch,dinner,snack,note})input.addTextChangedListener(dirty);
  Button save=new Button(this);save.setText("식단 저장");
  save.setOnClickListener(v->{
   current[0].date=date;current[0].breakfast=breakfast.getText().toString();current[0].lunch=lunch.getText().toString();current[0].dinner=dinner.getText().toString();current[0].snack=snack.getText().toString();current[0].note=note.getText().toString();
   save.setEnabled(false);for(EditText input:new EditText[]{breakfast,lunch,dinner,snack,note})input.setEnabled(false);getSharedPreferences("prefs",MODE_PRIVATE).edit().putBoolean("care_"+date+"_pending",true).apply();saveLocalCare(current[0]);WidgetUpdater.updateAll(this);toast("기기에 저장했어요");
   Executors.newSingleThreadExecutor().execute(()->{try{if(current[0].id.isEmpty())current[0].id=NotionClient.loadCare(token,date).id;NotionClient.saveCare(token,current[0],carePhase(date));saveLocalCare(current[0]);getSharedPreferences("prefs",MODE_PRIVATE).edit().putBoolean("care_"+date+"_pending",false).apply();WidgetUpdater.updateAll(this);runOnUiThread(()->{save.setEnabled(true);for(EditText input:new EditText[]{breakfast,lunch,dinner,snack,note})input.setEnabled(true);toast("노션에도 동기화했어요");});}catch(Exception e){runOnUiThread(()->{save.setEnabled(true);for(EditText input:new EditText[]{breakfast,lunch,dinner,snack,note})input.setEnabled(true);toast("노션 동기화 실패 · 기기 저장본은 유지돼요. 저장을 다시 누르면 재시도해요.");});}});
  });
  list.addView(save,new LinearLayout.LayoutParams(-1,dp(52)));

  loading.setVisibility(View.VISIBLE);
  Executors.newSingleThreadExecutor().execute(()->{try{NotionClient.CareEntry x=NotionClient.loadCare(token,date);runOnUiThread(()->{if(!edited[0]&&!getSharedPreferences("prefs",MODE_PRIVATE).getBoolean("care_"+date+"_pending",false)&&hasCareContent(x)){current[0]=x;saveLocalCare(x);breakfast.setText(x.breakfast);lunch.setText(x.lunch);dinner.setText(x.dinner);snack.setText(x.snack);note.setText(x.note);WidgetUpdater.updateAll(this);}loading.setVisibility(View.GONE);});}catch(Exception e){runOnUiThread(()->loading.setVisibility(View.GONE));}});
 }

 private void singleMeal(String field){
  String label;switch(field){case"breakfast":label="아침";break;case"lunch":label="점심";break;case"dinner":label="저녁";break;case"snack":label="간식";break;default:getIntent().removeExtra("care_field");care();return;}
  final String date=getIntent().getStringExtra("care_date")==null?new SimpleDateFormat("yyyy-MM-dd",Locale.US).format(new Date()):getIntent().getStringExtra("care_date");
  list.removeAllViews();list.addView(text(date+" · "+label,22));
  EditText input=field(label+"에 먹은 내용","");input.setMinLines(3);input.setGravity(Gravity.TOP);input.setTextSize(18);list.addView(input,new LinearLayout.LayoutParams(-1,dp(140)));
  TextView status=text("기록 불러오는 중…",13);list.addView(status);
  Button save=new Button(this);save.setText("저장");save.setEnabled(false);list.addView(save,new LinearLayout.LayoutParams(-1,dp(52)));
  Button retry=new Button(this);retry.setText("다시 불러오기");retry.setVisibility(View.GONE);retry.setOnClickListener(v->singleMeal(field));list.addView(retry);
  input.setEnabled(false);final NotionClient.CareEntry[] current={loadLocalCare(date)};
  loading.setVisibility(View.VISIBLE);
  Executors.newSingleThreadExecutor().execute(()->{try{
   NotionClient.CareEntry remote=NotionClient.loadCare(token,date);
   boolean pending=getSharedPreferences("prefs",MODE_PRIVATE).getBoolean("care_"+date+"_pending",false);
   if(pending){current[0].id=remote.id;}else{current[0]=remote;saveLocalCare(remote);}
   runOnUiThread(()->{NotionClient.CareEntry x=current[0];input.setText(field.equals("breakfast")?x.breakfast:field.equals("lunch")?x.lunch:field.equals("dinner")?x.dinner:x.snack);input.setEnabled(true);save.setEnabled(true);status.setText("");loading.setVisibility(View.GONE);input.requestFocus();getWindow().setSoftInputMode(android.view.WindowManager.LayoutParams.SOFT_INPUT_ADJUST_RESIZE);((android.view.inputmethod.InputMethodManager)getSystemService(INPUT_METHOD_SERVICE)).showSoftInput(input,android.view.inputmethod.InputMethodManager.SHOW_IMPLICIT);});
  }catch(Exception e){runOnUiThread(()->{loading.setVisibility(View.GONE);status.setText("불러오지 못했어요. 기존 식단을 보호하려면 다시 불러와 주세요.");retry.setVisibility(View.VISIBLE);});}});
  save.setOnClickListener(v->{String value=input.getText().toString();NotionClient.CareEntry x=current[0];switch(field){case"breakfast":x.breakfast=value;break;case"lunch":x.lunch=value;break;case"dinner":x.dinner=value;break;case"snack":x.snack=value;break;}
   save.setEnabled(false);input.setEnabled(false);status.setText("저장 중…");
   getSharedPreferences("prefs",MODE_PRIVATE).edit().putBoolean("care_"+date+"_pending",true).apply();saveLocalCare(x);
   Executors.newSingleThreadExecutor().execute(()->{try{NotionClient.saveCare(token,x,carePhase(date));saveLocalCare(x);getSharedPreferences("prefs",MODE_PRIVATE).edit().putBoolean("care_"+date+"_pending",false).apply();WidgetUpdater.updateAll(this);runOnUiThread(()->{toast("저장했어요");finish();});}catch(Exception e){WidgetUpdater.updateAll(this);runOnUiThread(()->{save.setEnabled(true);input.setEnabled(true);status.setText("폰에는 저장됐어요. 노션 동기화는 저장을 눌러 재시도해 주세요.");});}});
  });
 }

 private NotionClient.CareEntry loadLocalCare(String date){android.content.SharedPreferences p=getSharedPreferences("prefs",MODE_PRIVATE);NotionClient.CareEntry x=new NotionClient.CareEntry();x.date=date;x.id=p.getString("care_"+date+"_id","");x.breakfast=p.getString("care_"+date+"_breakfast","");x.lunch=p.getString("care_"+date+"_lunch","");x.dinner=p.getString("care_"+date+"_dinner","");x.snack=p.getString("care_"+date+"_snack","");x.note=p.getString("care_"+date+"_note","");return x;}
 private void saveLocalCare(NotionClient.CareEntry x){getSharedPreferences("prefs",MODE_PRIVATE).edit().putString("care_"+x.date+"_id",x.id).putString("care_"+x.date+"_breakfast",x.breakfast).putString("care_"+x.date+"_lunch",x.lunch).putString("care_"+x.date+"_dinner",x.dinner).putString("care_"+x.date+"_snack",x.snack).putString("care_"+x.date+"_note",x.note).apply();}
 private boolean hasCareContent(NotionClient.CareEntry x){return x!=null&&(!x.id.isEmpty()||!x.breakfast.trim().isEmpty()||!x.lunch.trim().isEmpty()||!x.dinner.trim().isEmpty()||!x.snack.trim().isEmpty()||!x.note.trim().isEmpty());}
 private String carePhase(String value){try{SimpleDateFormat f=new SimpleDateFormat("yyyy-MM-dd",Locale.US);f.setLenient(false);Date day=f.parse(value),start=f.parse(getSharedPreferences("prefs",MODE_PRIVATE).getString("period_start","")),end=f.parse(getSharedPreferences("prefs",MODE_PRIVATE).getString("period_end",""));if(day==null||start==null||end==null)return"";int cycle=getSharedPreferences("prefs",MODE_PRIVATE).getInt("cycle_length",28);long unit=86400000L;int n=(int)(((day.getTime()-start.getTime())/unit%cycle+cycle)%cycle),period=Math.max(1,(int)((end.getTime()-start.getTime())/unit)+1),ovulation=cycle-14;if(n<period)return"🫧";if(n<ovulation)return"💊";if(n==ovulation)return"✦";return"🍦";}catch(Exception e){return"";}}
 private void tokenDialog(){EditText i=field("Notion 내부 통합 시크릿",token);i.setInputType(129);new AlertDialog.Builder(this).setTitle("연결 설정").setView(i).setNegativeButton("취소",null).setNeutralButton("토큰 지우기",(d,w)->{getSharedPreferences("prefs",MODE_PRIVATE).edit().clear().apply();token="";showToken();}).setPositiveButton("저장",(d,w)->{token=i.getText().toString().trim();getSharedPreferences("prefs",MODE_PRIVATE).edit().putString("token",token).apply();load();}).show();}
 private void error(Exception e){loading.setVisibility(View.GONE);toast("오류: "+(e.getMessage()==null?"알 수 없는 오류":e.getMessage()));}private void toast(String s){Toast.makeText(this,s,Toast.LENGTH_LONG).show();}
}
