package com.hyeona.widget;
import org.json.*;import java.io.*;import java.net.*;import java.nio.charset.StandardCharsets;import java.text.SimpleDateFormat;import java.util.*;
final class NotionClient{
 private static final String CAL="3cd946f45bc2803da355faf7751fb866",BLEED="c07869fbaaa746a593663a5ff92ebd22",WISH="3cd946f45bc280cb875cfe998bc81776",MEMO="3cd946f45bc280dbafaec68c50665447",TODO="3cd946f45bc280599404f0b86f771142",ROUT="9d7cbaca00274f12a6d016927ffb0296",BRAIN="3ce946f45bc281ab9e97d2aa17504ea9",CARE="3e4946f45bc28044bdf0ed652e378396";
 static final class Item{String id="",title="",date="",memo="",month="",status="";double amount;boolean done;Item copy(){Item y=new Item();y.id=id;y.title=title;y.date=date;y.memo=memo;y.month=month;y.status=status;y.amount=amount;y.done=done;return y;}}
 static final class CareEntry{String id="",date="",breakfast="",lunch="",dinner="",snack="",note="";}
 private static String db(String t){switch(t){case"calendar":return CAL;case"bleeding":return BLEED;case"wishlist":return WISH;case"memo":return MEMO;case"todo":return TODO;default:return ROUT;}}
 private static String titleKey(String token,String database)throws Exception{JSONObject p=req(token,"GET","databases/"+database,null).getJSONObject("properties");if(TODO.equals(database)&&!p.has("완료"))req(token,"PATCH","databases/"+database,new JSONObject().put("properties",new JSONObject().put("완료",new JSONObject().put("checkbox",new JSONObject()))));Iterator<String>k=p.keys();while(k.hasNext()){String n=k.next();if("title".equals(p.getJSONObject(n).optString("type")))return n;}throw new Exception("데이터베이스에 제목 속성이 필요해요");}
 static List<Item> query(String token,String type)throws Exception{String database=db(type),key=titleKey(token,database);JSONObject b=new JSONObject().put("page_size",100);if(type.equals("bleeding")){String m=(Calendar.getInstance().get(Calendar.MONTH)+1)+"월";b.put("filter",new JSONObject().put("property","월").put("select",new JSONObject().put("equals",m)));}JSONArray a=req(token,"POST","databases/"+database+"/query",b).getJSONArray("results");List<Item>out=new ArrayList<>();for(int i=0;i<a.length();i++){JSONObject pg=a.getJSONObject(i),p=pg.getJSONObject("properties");Item x=new Item();x.id=pg.getString("id");x.title=title(p.optJSONObject(key));JSONObject q=p.optJSONObject("완료");if(q!=null)x.done=q.optBoolean("checkbox");if(type.equals("calendar")){q=p.optJSONObject("날짜");if(q!=null&&!q.isNull("date"))x.date=q.optJSONObject("date").optString("start");}if(type.equals("bleeding")){q=p.optJSONObject("금액(만원)");if(q!=null)x.amount=q.optDouble("number",0);x.memo=text(p.optJSONObject("메모"));q=p.optJSONObject("월");if(q!=null&&!q.isNull("select"))x.month=q.optJSONObject("select").optString("name");}if(type.equals("wishlist")){q=p.optJSONObject("상태");if(q!=null&&!q.isNull("status"))x.status=q.optJSONObject("status").optString("name");}out.add(x);}return out;}
 static void create(String t,String type,Item x)throws Exception{req(t,"POST","pages",new JSONObject().put("parent",new JSONObject().put("database_id",db(type))).put("properties",props(t,type,x)));}static void update(String t,String type,Item x)throws Exception{req(t,"PATCH","pages/"+x.id,new JSONObject().put("properties",props(t,type,x)));}static void delete(String t,String id)throws Exception{req(t,"PATCH","pages/"+id,new JSONObject().put("archived",true));}
 static String loadBrain(String t)throws Exception{return text(req(t,"GET","pages/"+BRAIN,null).getJSONObject("properties").optJSONObject("내용"));}static void saveBrain(String t,String v)throws Exception{String s=v.substring(0,Math.min(1900,v.length()));JSONObject r=new JSONObject().put("rich_text",new JSONArray().put(new JSONObject().put("text",new JSONObject().put("content",s))));req(t,"PATCH","pages/"+BRAIN,new JSONObject().put("properties",new JSONObject().put("내용",r)));}
 static CareEntry loadCare(String token,String date)throws Exception{
  DbShape s=careDb(token); CareEntry out=new CareEntry(); out.date=date;
  JSONObject body=new JSONObject().put("page_size",10).put("filter",new JSONObject().put("property",s.date).put("date",new JSONObject().put("equals",date)));
  JSONArray a=req(token,"POST","databases/"+s.id+"/query",body).getJSONArray("results"); if(a.length()==0)return out;
  JSONObject page=a.getJSONObject(0),p=page.getJSONObject("properties");out.id=page.optString("id");out.breakfast=text(p.optJSONObject("아침"));out.lunch=text(p.optJSONObject("점심"));out.dinner=text(p.optJSONObject("저녁"));out.snack=text(p.optJSONObject("간식"));out.note=text(p.optJSONObject("관리 메모"));return out;
 }
 static void saveCare(String token,CareEntry x,String phase)throws Exception{
  DbShape s=careDb(token);JSONObject p=new JSONObject();
  p.put(s.title,new JSONObject().put("title",rich(x.date+" 식단"))).put(s.date,new JSONObject().put("date",new JSONObject().put("start",x.date)));
  p.put("아침",new JSONObject().put("rich_text",rich(x.breakfast.trim()))).put("점심",new JSONObject().put("rich_text",rich(x.lunch.trim()))).put("저녁",new JSONObject().put("rich_text",rich(x.dinner.trim()))).put("간식",new JSONObject().put("rich_text",rich(x.snack.trim()))).put("관리 메모",new JSONObject().put("rich_text",rich((phase.isEmpty()?"":phase+" · ")+x.note.trim())));
  JSONObject body=new JSONObject().put("properties",p);if(x.id.isEmpty())body.put("parent",new JSONObject().put("database_id",s.id));
  req(token,x.id.isEmpty()?"POST":"PATCH",x.id.isEmpty()?"pages":"pages/"+x.id,body);
 }
 private static JSONArray rich(String value)throws Exception{return new JSONArray().put(new JSONObject().put("text",new JSONObject().put("content",value.substring(0,Math.min(1800,value.length())))));}
 private static final class DbShape{String id="",title="",date="",note="";}
 private static DbShape careDb(String token)throws Exception{
  String id=CARE;JSONObject props=req(token,"GET","databases/"+id,null).getJSONObject("properties");DbShape s=new DbShape();s.id=id;
  Iterator<String> keys=props.keys();while(keys.hasNext()){String k=keys.next(),type=props.getJSONObject(k).optString("type");if("title".equals(type))s.title=k;else if("date".equals(type)&&s.date.isEmpty())s.date=k;}
  JSONObject add=new JSONObject();if(s.date.isEmpty())add.put("날짜",new JSONObject().put("date",new JSONObject()));for(String k:new String[]{"아침","점심","저녁","간식","관리 메모"})if(!props.has(k))add.put(k,new JSONObject().put("rich_text",new JSONObject()));if(add.length()>0){req(token,"PATCH","databases/"+id,new JSONObject().put("properties",add));if(s.date.isEmpty())s.date="날짜";}
  if(s.title.isEmpty())throw new Exception("식단 데이터베이스에 제목 속성이 필요해요");return s;
 }
 private static JSONObject props(String token,String type,Item x)throws Exception{String n=x.title.substring(0,Math.min(500,x.title.length()));JSONObject p=new JSONObject().put(titleKey(token,db(type)),new JSONObject().put("title",new JSONArray().put(new JSONObject().put("text",new JSONObject().put("content",n)))));if(type.equals("calendar")||type.equals("bleeding")||type.equals("routine")||type.equals("todo"))p.put("완료",new JSONObject().put("checkbox",x.done));if(type.equals("calendar"))p.put("날짜",new JSONObject().put("date",new JSONObject().put("start",x.date)));if(type.equals("bleeding")){String m=x.month.isEmpty()?new SimpleDateFormat("M월",Locale.KOREAN).format(new Date()):x.month;p.put("월",new JSONObject().put("select",new JSONObject().put("name",m))).put("금액(만원)",new JSONObject().put("number",x.amount));String me=x.memo.substring(0,Math.min(1000,x.memo.length()));p.put("메모",new JSONObject().put("rich_text",new JSONArray().put(new JSONObject().put("text",new JSONObject().put("content",me)))));}if(type.equals("wishlist")&&!x.status.isEmpty())p.put("상태",new JSONObject().put("status",new JSONObject().put("name",x.status)));return p;}
 private static String title(JSONObject p){return p==null?"":join(p.optJSONArray("title"));}private static String text(JSONObject p){return p==null?"":join(p.optJSONArray("rich_text"));}private static String join(JSONArray a){if(a==null)return"";StringBuilder s=new StringBuilder();for(int i=0;i<a.length();i++){JSONObject o=a.optJSONObject(i);if(o!=null)s.append(o.optString("plain_text"));}return s.toString();}
 private static JSONObject req(String token,String method,String path,JSONObject body)throws Exception{HttpURLConnection h=(HttpURLConnection)new URL("https://api.notion.com/v1/"+path).openConnection();h.setRequestMethod(method);h.setRequestProperty("Authorization","Bearer "+token);h.setRequestProperty("Notion-Version","2022-06-28");h.setRequestProperty("Content-Type","application/json");h.setConnectTimeout(15000);h.setReadTimeout(20000);if(body!=null){h.setDoOutput(true);try(OutputStream o=h.getOutputStream()){o.write(body.toString().getBytes(StandardCharsets.UTF_8));}}int code=h.getResponseCode();BufferedReader r=new BufferedReader(new InputStreamReader(code<400?h.getInputStream():h.getErrorStream()));StringBuilder s=new StringBuilder();String line;while((line=r.readLine())!=null)s.append(line);if(code>=400){String m;try{m=new JSONObject(s.toString()).optString("message",s.toString());}catch(Exception e){m=s.toString();}throw new Exception(m);}return new JSONObject(s.toString());}
}
