package com.hyeona.widget;
import org.json.*;import java.io.*;import java.net.*;import java.nio.charset.StandardCharsets;import java.text.SimpleDateFormat;import java.util.*;
final class NotionClient{
 private static final String CAL="3cd946f45bc2803da355faf7751fb866",BLEED="c07869fbaaa746a593663a5ff92ebd22",WISH="3cd946f45bc280cb875cfe998bc81776",MEMO="3cd946f45bc280dbafaec68c50665447",ROUT="9d7cbaca00274f12a6d016927ffb0296",BRAIN="3ce946f45bc281ab9e97d2aa17504ea9";
 static final class Item{String id="",title="",date="",memo="",month="",status="";double amount;boolean done;Item copy(){Item y=new Item();y.id=id;y.title=title;y.date=date;y.memo=memo;y.month=month;y.status=status;y.amount=amount;y.done=done;return y;}}
 private static String db(String t){switch(t){case"calendar":return CAL;case"bleeding":return BLEED;case"wishlist":return WISH;case"memo":return MEMO;default:return ROUT;}}private static String tk(String t){return t.equals("calendar")||t.equals("wishlist")?"이름":t.equals("memo")?"제목":"항목";}
 static List<Item> query(String token,String type)throws Exception{JSONObject b=new JSONObject().put("page_size",100);if(type.equals("bleeding")){String m=(Calendar.getInstance().get(Calendar.MONTH)+1)+"월";b.put("filter",new JSONObject().put("property","월").put("select",new JSONObject().put("equals",m)));}JSONArray a=req(token,"POST","databases/"+db(type)+"/query",b).getJSONArray("results");List<Item>out=new ArrayList<>();for(int i=0;i<a.length();i++){JSONObject pg=a.getJSONObject(i),p=pg.getJSONObject("properties");Item x=new Item();x.id=pg.getString("id");x.title=title(p.optJSONObject(tk(type)));JSONObject q=p.optJSONObject("완료");if(q!=null)x.done=q.optBoolean("checkbox");if(type.equals("calendar")){q=p.optJSONObject("날짜");if(q!=null&&!q.isNull("date"))x.date=q.optJSONObject("date").optString("start");}if(type.equals("bleeding")){q=p.optJSONObject("금액(만원)");if(q!=null)x.amount=q.optDouble("number",0);x.memo=text(p.optJSONObject("메모"));q=p.optJSONObject("월");if(q!=null&&!q.isNull("select"))x.month=q.optJSONObject("select").optString("name");}if(type.equals("wishlist")){q=p.optJSONObject("상태");if(q!=null&&!q.isNull("status"))x.status=q.optJSONObject("status").optString("name");}out.add(x);}return out;}
 static void create(String t,String type,Item x)throws Exception{req(t,"POST","pages",new JSONObject().put("parent",new JSONObject().put("database_id",db(type))).put("properties",props(type,x)));}static void update(String t,String type,Item x)throws Exception{req(t,"PATCH","pages/"+x.id,new JSONObject().put("properties",props(type,x)));}static void delete(String t,String id)throws Exception{req(t,"PATCH","pages/"+id,new JSONObject().put("archived",true));}
 static String loadBrain(String t)throws Exception{return text(req(t,"GET","pages/"+BRAIN,null).getJSONObject("properties").optJSONObject("내용"));}static void saveBrain(String t,String v)throws Exception{String s=v.substring(0,Math.min(1900,v.length()));JSONObject r=new JSONObject().put("rich_text",new JSONArray().put(new JSONObject().put("text",new JSONObject().put("content",s))));req(t,"PATCH","pages/"+BRAIN,new JSONObject().put("properties",new JSONObject().put("내용",r)));}
 private static JSONObject props(String type,Item x)throws Exception{String n=x.title.substring(0,Math.min(500,x.title.length()));JSONObject p=new JSONObject().put(tk(type),new JSONObject().put("title",new JSONArray().put(new JSONObject().put("text",new JSONObject().put("content",n)))));if(type.equals("calendar")||type.equals("bleeding")||type.equals("routine"))p.put("완료",new JSONObject().put("checkbox",x.done));if(type.equals("calendar"))p.put("날짜",new JSONObject().put("date",new JSONObject().put("start",x.date)));if(type.equals("bleeding")){String m=x.month.isEmpty()?new SimpleDateFormat("M월",Locale.KOREAN).format(new Date()):x.month;p.put("월",new JSONObject().put("select",new JSONObject().put("name",m))).put("금액(만원)",new JSONObject().put("number",x.amount));String me=x.memo.substring(0,Math.min(1000,x.memo.length()));p.put("메모",new JSONObject().put("rich_text",new JSONArray().put(new JSONObject().put("text",new JSONObject().put("content",me)))));}if(type.equals("wishlist")&&!x.status.isEmpty())p.put("상태",new JSONObject().put("status",new JSONObject().put("name",x.status)));return p;}
 private static String title(JSONObject p){return p==null?"":join(p.optJSONArray("title"));}private static String text(JSONObject p){return p==null?"":join(p.optJSONArray("rich_text"));}private static String join(JSONArray a){if(a==null)return"";StringBuilder s=new StringBuilder();for(int i=0;i<a.length();i++){JSONObject o=a.optJSONObject(i);if(o!=null)s.append(o.optString("plain_text"));}return s.toString();}
 private static JSONObject req(String token,String method,String path,JSONObject body)throws Exception{HttpURLConnection h=(HttpURLConnection)new URL("https://api.notion.com/v1/"+path).openConnection();h.setRequestMethod(method);h.setRequestProperty("Authorization","Bearer "+token);h.setRequestProperty("Notion-Version","2022-06-28");h.setRequestProperty("Content-Type","application/json");h.setConnectTimeout(15000);h.setReadTimeout(20000);if(body!=null){h.setDoOutput(true);try(OutputStream o=h.getOutputStream()){o.write(body.toString().getBytes(StandardCharsets.UTF_8));}}int code=h.getResponseCode();BufferedReader r=new BufferedReader(new InputStreamReader(code<400?h.getInputStream():h.getErrorStream()));StringBuilder s=new StringBuilder();String line;while((line=r.readLine())!=null)s.append(line);if(code>=400){String m;try{m=new JSONObject(s.toString()).optString("message",s.toString());}catch(Exception e){m=s.toString();}throw new Exception(m);}return new JSONObject(s.toString());}
}
